var dir_118c31fa8f614d61ca8ba0850500d19d =
[
    [ "conical", "dir_8d501718c4f66418890341554074a2a3.html", "dir_8d501718c4f66418890341554074a2a3" ],
    [ "jacobi", "dir_07ea5044f667393972989452db362fa0.html", "dir_07ea5044f667393972989452db362fa0" ],
    [ "legendre_poly", "dir_b77e50d27b2179291c6f54308608409a.html", "dir_b77e50d27b2179291c6f54308608409a" ],
    [ "sldfesq", "dir_dcfb2d49c2353e99ac291c5d15fa926a.html", "dir_dcfb2d49c2353e99ac291c5d15fa926a" ],
    [ "angular_product_quadrature.cc", "db/dbc/angular__product__quadrature_8cc.html", null ],
    [ "angular_product_quadrature.h", "da/daf/angular__product__quadrature_8h.html", "da/daf/angular__product__quadrature_8h" ],
    [ "angular_quadrature_base.cc", "d8/de6/angular__quadrature__base_8cc.html", null ],
    [ "angular_quadrature_base.h", "d5/d27/angular__quadrature__base_8h.html", "d5/d27/angular__quadrature__base_8h" ],
    [ "angular_quadrature_prodcust.cc", "d2/d31/angular__quadrature__prodcust_8cc.html", null ],
    [ "curvilinear_angular_quadrature.h", "da/dec/curvilinear__angular__quadrature_8h.html", "da/dec/curvilinear__angular__quadrature_8h" ],
    [ "cylindrical_angular_quadrature.cc", "dc/dd2/cylindrical__angular__quadrature_8cc.html", null ],
    [ "cylindrical_angular_quadrature.h", "df/da7/cylindrical__angular__quadrature_8h.html", "df/da7/cylindrical__angular__quadrature_8h" ],
    [ "point_quadrature.cc", "d8/d3b/point__quadrature_8cc.html", null ],
    [ "point_quadrature.h", "d5/d44/point__quadrature_8h.html", "d5/d44/point__quadrature_8h" ],
    [ "quadrature.cc", "d6/d90/quadrature_8cc.html", null ],
    [ "quadrature.h", "d5/d4c/quadrature_8h.html", "d5/d4c/quadrature_8h" ],
    [ "quadrature_gausschebyshev.cc", "d4/d44/quadrature__gausschebyshev_8cc.html", "d4/d44/quadrature__gausschebyshev_8cc" ],
    [ "quadrature_gausschebyshev.h", "d0/d18/quadrature__gausschebyshev_8h.html", "d0/d18/quadrature__gausschebyshev_8h" ],
    [ "quadrature_gausslegendre.cc", "dd/dda/quadrature__gausslegendre_8cc.html", "dd/dda/quadrature__gausslegendre_8cc" ],
    [ "quadrature_gausslegendre.h", "d7/de2/quadrature__gausslegendre_8h.html", "d7/de2/quadrature__gausslegendre_8h" ],
    [ "quadrature_hexahedron.cc", "d2/d95/quadrature__hexahedron_8cc.html", null ],
    [ "quadrature_hexahedron.h", "db/d6b/quadrature__hexahedron_8h.html", "db/d6b/quadrature__hexahedron_8h" ],
    [ "quadrature_line.h", "d7/dda/quadrature__line_8h.html", "d7/dda/quadrature__line_8h" ],
    [ "quadrature_quadrilateral.cc", "d9/d06/quadrature__quadrilateral_8cc.html", null ],
    [ "quadrature_quadrilateral.h", "d8/d20/quadrature__quadrilateral_8h.html", "d8/d20/quadrature__quadrilateral_8h" ],
    [ "quadrature_tetrahedron.cc", "d9/d96/quadrature__tetrahedron_8cc.html", null ],
    [ "quadrature_tetrahedron.h", "d6/da3/quadrature__tetrahedron_8h.html", "d6/da3/quadrature__tetrahedron_8h" ],
    [ "quadrature_triangle.cc", "dc/d00/quadrature__triangle_8cc.html", null ],
    [ "quadrature_triangle.h", "df/d98/quadrature__triangle_8h.html", "df/d98/quadrature__triangle_8h" ],
    [ "quadrature_wedge.cc", "db/da1/quadrature__wedge_8cc.html", null ],
    [ "quadrature_wedge.h", "da/de7/quadrature__wedge_8h.html", "da/de7/quadrature__wedge_8h" ],
    [ "spherical_angular_quadrature.cc", "da/d3b/spherical__angular__quadrature_8cc.html", null ],
    [ "spherical_angular_quadrature.h", "de/d43/spherical__angular__quadrature_8h.html", "de/d43/spherical__angular__quadrature_8h" ]
];