dog = Dog.Create({breed="lua"})
dog:Bark()

simple_dog = Dog.new()
simple_dog:Bark()

-- -- Setup mesh
-- nodes={}
-- N=10
-- L=2
-- xmin = -L/2
-- dx = L/N
-- for i=1,(N+1) do
--     k=i-1
--     nodes[i] = xmin + k*dx
-- end
--
-- meshgen1 = opensn.A.OrthogonalMeshGenerator.new({ node_sets = {nodes,nodes} })

-- meshgen1 = opensn.OrthogonalMeshGenerator.new({ node_sets = {nodes,nodes} })
-- meshgen1:Execute()
 
-- -- Set Material IDs
-- opensn.VolumeMesherSetMatIDToAll(0)
--
-- D = {1.0}
-- Q = {0.0}
-- XSa = {0.0}
-- function D_coef(i,x,y,z)
--     return D[i+1]
-- end
-- function Q_ext(i,x,y,z)
--     return Q[i+1]
-- end
-- function Sigma_a(i,x,y,z)
--     return XSa[i+1]
-- end
--
-- -- Set boundary IDs
-- -- xmin,xmax,ymin,ymax,zmin,zmax
-- e_vol = opensn.RPPLogicalVolume.new({xmin=0.99999,xmax=1000.0  , infy=true, infz=true})
-- w_vol = opensn.RPPLogicalVolume.new({xmin=-1000.0,xmax=-0.99999, infy=true, infz=true})
-- n_vol = opensn.RPPLogicalVolume.new({ymin=0.99999,ymax=1000.0  , infx=true, infz=true})
-- s_vol = opensn.RPPLogicalVolume.new({ymin=-1000.0,ymax=-0.99999, infx=true, infz=true})
--
-- e_bndry = 0
-- w_bndry = 1
-- n_bndry = 2
-- s_bndry = 3
--
-- opensn.VolumeMesherSetProperty(BNDRYID_FROMLOGICAL, e_vol, e_bndry)
-- opensn.VolumeMesherSetProperty(BNDRYID_FROMLOGICAL, w_vol, w_bndry)
-- opensn.VolumeMesherSetProperty(BNDRYID_FROMLOGICAL, n_vol, n_bndry)
-- opensn.VolumeMesherSetProperty(BNDRYID_FROMLOGICAL, s_vol, s_bndry)
--
-- -- Add material properties
--
-- -- CFEM solver
-- phys1 = opensn.CFEMDiffusionSolver.new()
--
-- phys1:SetBasicOption("residual_tolerance", 1E-8)
--
-- phys1:SetBCProperty("boundary_type", e_bndry, "robin", 0.25, 0.5, 0.0)
-- phys1:SetBCProperty("boundary_type", n_bndry, "reflecting")
-- phys1:SetBCProperty("boundary_type", s_bndry, "reflecting")
-- phys1:SetBCProperty("boundary_type", w_bndry, "robin", 0.25, 0.5, 1.0)
--
-- phys1:Initialize()
-- phys1:Execute()
--
-- -- Get field functions
-- fflist, count = phys1:GetFieldFunctionList(phys1)
--
-- -- Export VTU
-- if (master_export == nil) then
--     opensn.ExportFieldFunctionToVTK(fflist[1], "CFEMDiff2D_linear")
-- end
--
-- --############################################### Line plot
-- cline = opensn.FFInterpolation.new(LINE)
-- cline:SetProperty(LINE_FIRSTPOINT, -L/2, 0.0, 0.0)
-- cline:SetProperty(LINE_SECONDPOINT, L/2, 0.0, 0.0)
-- cline:SetProperty(LINE_NUMBEROFPOINTS, 50)
-- cline:SetProperty(ADD_FIELDFUNCTION, fflist[1])
--
-- cline:Initialize()
-- cline:Execute()
--
-- if (master_export == nil) then
--     cline:ExportPython(cline)
-- end
--
-- -- Volume integrations
--
-- -- PostProcessors
-- max_val = opensn.AggregateNodalValuePostProcessor.new
-- ({
--     name = "maxval",
--     field_function = math.floor(fflist[1]),
--     operation = "max"
-- })
-- -- opensn.ExecutePostProcessors({maxval})
-- opensn.ExecutePostProcessors({"maxval"})
