name: Regression Tests

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: configure
        shell: bash
        run: |
          export MODULEPATH=/scratch-local/software/modulefiles
          module load opensn/gcc/12.3.0
          ./configure.sh
      - name: make
        shell: bash
        run: |
          export MODULEPATH=/scratch-local/software/modulefiles
          module load opensn/gcc/12.3.0
          cmake --build build --parallel 64
      - name: test
        shell: bash
        run: |
          export MODULEPATH=/scratch-local/software/modulefiles
          module load opensn/gcc/12.3.0
          test/run_tests -d test/ -j 32 -v 1 -w 3
      - name: test tutorials
        shell: bash
        run: |
          export MODULEPATH=/scratch-local/software/modulefiles
          module load opensn/gcc/12.3.0
          test/run_tests -d doc/tutorials -j 32 -v 1 -w 3
